name: CI

on: 
  push:
    branches: 
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@source
      with:
        submodules: true

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.55.6'
    
    - name: Build
      run: hugo
    
    - name: Deploy
      run: |
        git config --local user.email "softball.22.5113@gmail.com"
        git config --local user.name "Komei22"
        git commit -m "Update docs/"
        git subtree push --prefix docs/ origin master
